### ISSUE TITLE
Got two enigma's , one of them started to throw error even if its available on the net. Plugin 1.9, HA 2024.10.0

### ISSUE THREAD

**Issue by marcinprzybysz86** [cinzas/homeassistant-enigma-player#14]
I got Plugin 1.9, HA 2024.10.0. Few days ago (on version 2024.9.x of HA) my second enigma2 device become unavailable.
Yet it has network connection, works fine, can access openwebif.
 
Error message in HA core log:

```
Źródło: helpers/entity_platform.py:724
integracja: Odtwarzacz mediów ([dokumentacja](https://www.home-assistant.io/integrations/media_player), [Problemy](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+media_player%22))
Pierwsze zdarzenie: 09:50:55 (1 zdarzenia)
Ostatnio zalogowany: 09:50:55

enigma: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 724, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1300, in async_device_update
    await self.async_update()
  File "/config/custom_components/enigma/media_player.py", line 219, in async_update
    await self.load_sources()
  File "/config/custom_components/enigma/media_player.py", line 154, in load_sources
    reference = urllib.parse.quote_plus(await self.get_bouquet_reference())
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/enigma/media_player.py", line 176, in get_bouquet_reference
    return soup.find('e2servicereference').renderContents().decode('UTF8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'renderContents'
```

Config:

```
enigma: 
  devices:
    - host: 192.168.1.197
      port: 80
      name: enigma2 salon
      timeout: 30
      username: root
      password: ............
      picon: picon
    - host: 192.168.1.131   <<-- this entity is not working
      port: 80
      name: enigma2 sypialnia 
      username: root
      password: ........
      timeout: 30
      picon: picon
```

![enigma2entity](https://github.com/user-attachments/assets/6d3f9565-7879-483d-bb9c-7c2d22457a94)

**Comment by marcinprzybysz86** [comment]
sorry, wrong user buquet in notify settings was the cause (I changed channel list recently).

**Comment by cinzas** [comment]
Glad you solved it :)
