### ISSUE TITLE
Since Update today to newest HA version I get errors in the logfile

### ISSUE THREAD

**Issue by fft1010** [cinzas/homeassistant-enigma-player#8]
Hi,
today ways a HA Update (Sorry, cannot find the Version number). The log directly after the boot was fine, but about 20 Minutes later I got this error in the logfile from _ONE_ of my enigmas. The "funny" thing. Usually I had a lot of errors from the _other_ enigma. I am investigating into the errors of the other enigma, I assume it has to to with how it goes into sleep mode or "off". The one that has the errors below is _ON_... Yesterday this very same machine did not have any errors, regardless if on or off.

I don't know what the problem is. In the user Interface it seems to work as it should.

```
2024-01-31 15:34:15.674 WARNING (MainThread) [homeassistant.helpers.entity] Entity media_player.wz_vu (<class 'custom_components.enigma.media_player.EnigmaMediaPlayer'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <MediaPlayerEntityFeature.PAUSE|VOLUME_SET|VOLUME_MUTE|PREVIOUS_TRACK|NEXT_TRACK|TURN_ON|TURN_OFF|PLAY_MEDIA|VOLUME_STEP|SELECT_SOURCE|PLAY: 20413>, please create a bug report at https://github.com/cinzas/homeassistant-enigma-player/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-01-31 15:54:45.942 WARNING (MainThread) [homeassistant.components.media_player] Updating enigma media_player took longer than the scheduled update interval 0:00:10
2024-01-31 15:54:45.943 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.wz_vu is taking over 10 seconds
2024-01-31 15:54:55.946 WARNING (MainThread) [homeassistant.components.media_player] Updating enigma media_player took longer than the scheduled update interval 0:00:10
2024-01-31 15:55:05.947 WARNING (MainThread) [homeassistant.components.media_player] Updating enigma media_player took longer than the scheduled update interval 0:00:10
2024-01-31 15:55:15.948 WARNING (MainThread) [homeassistant.components.media_player] Updating enigma media_player took longer than the scheduled update interval 0:00:10
2024-01-31 15:55:25.949 WARNING (MainThread) [homeassistant.components.media_player] Updating enigma media_player took longer than the scheduled update interval 0:00:10
2024-01-31 15:55:35.953 WARNING (MainThread) [homeassistant.components.media_player] Updating enigma media_player took longer than the scheduled update interval 0:00:10
2024-01-31 15:55:45.953 WARNING (MainThread) [homeassistant.components.media_player] Updating enigma media_player took longer than the scheduled update interval 0:00:10
2024-01-31 15:55:55.954 WARNING (MainThread) [homeassistant.components.media_player] Updating enigma media_player took longer than the scheduled update interval 0:00:10
2024-01-31 15:56:05.956 WARNING (MainThread) [homeassistant.components.media_player] Updating enigma media_player took longer than the scheduled update interval 0:00:10
2024-01-31 15:56:15.956 WARNING (MainThread) [homeassistant.components.media_player] Updating enigma media_player took longer than the scheduled update interval 0:00:10
2024-01-31 15:56:25.962 WARNING (MainThread) [homeassistant.components.media_player] Updating enigma media_player took longer than the scheduled update interval 0:00:10
2024-01-31 15:56:35.963 WARNING (MainThread) [homeassistant.components.media_player] Updating enigma media_player took longer than the scheduled update interval 0:00:10
2024-01-31 15:56:45.965 WARNING (MainThread) [homeassistant.components.media_player] Updating enigma media_player took longer than the scheduled update interval 0:00:10
2024-01-31 15:56:47.598 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.wz_vu fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 628, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 668, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('192.168.90.143', 82)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 898, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1216, in async_device_update
    await self.async_update()
  File "/config/custom_components/enigma/media_player.py", line 203, in async_update
    powerstate_xml = await self.request_call('/web/powerstate')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/enigma/media_player.py", line 187, in request_call
    async with self._opener.get(uri, auth=aiohttp.BasicAuth(self._username, self._password)) as resp:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 578, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1235, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1000, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.90.143:82 ssl:default [Connect call failed ('192.168.90.143', 82)]
2024-01-31 16:07:43.922 WARNING (MainThread) [homeassistant.components.media_player] Error retrieving proxied image from http://192.168.90.143:82/picon/1_0_1_445E_453_1_C00000_0_0_0.png
```

**Comment by cinzas** [comment]
Hi @fft1010 

Did you solve the issue ?
This seems to be a connection issue with the box.

**Comment by fft1010** [comment]
Hi @cinzas ,
I noticed, that this happens, if I fully turn the enigma "fully off" Sorry, cannot remember exactly. The "off" where the enigma con be turned on by enigma remote only. I noticed that than (for sure) the webif is not available. if I only let it go to stadby, than everyhting works.
As other devices in HA behave different ("off" instead of logfile errors), I think this could be changed  in this implementation "somehow", but I am no programmer.

thanks
Juergen

**Comment by cinzas** [comment]
@fft1010 , that is correct.

The Enigma has these states

- Off
- On
- Standby
- Deep Standby

Unfortunately we cannot turn it on from HA if it is on the state off (no power) or on the deep standby (where you need the remote for that).

So I use my enigmas only with these states

- On
- Standby (which appears as off on HA)

I believe you are setting your enigma to Deep Standby, from where you cannot turn it on.

**Comment by fft1010** [comment]
Hi @cinzas ,
I know those states, and the problem is not, that I cannot turn the enigma "on" in state Deep Standby, the problem is, that the logfile of HA is filled up with error requests if enigma is in standby. (my personal problem was, that I have two enigmas, one by chance in deep standby and one in stanby; and  I wondered, why one filled up the logfile with errors, and the other not). I have other systems (Shelly Plug, e.g.) that I physically turn off (as they are on a second switchand only usedm if I work), and they produce no error in logfile if turned of (so definitely not power connected). So I assume, that there is a way to change this. But I do not have a real urge for changing this, it is just "uncomfortable", IMHO.

thanks you
Juergen

**Comment by cinzas** [comment]
You can always reduce the debug level on HA :)

**Comment by fft1010** [comment]
Hi @cinzas ,

Or I could turn HA off, than I won't see such errors not as well: :-)
Again: Noting major, but I think there is a way to let it catch from HA, if the machine is physically on the network. Works with google chromecast as well: If off, no errors.

```
2024-01-31 15:56:47.598 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.wz_vu fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 628, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 668, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('192.168.90.143', 82)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 898, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1216, in async_device_update
    await self.async_update()
  File "/config/custom_components/enigma/media_player.py", line 203, in async_update
    powerstate_xml = await self.request_call('/web/powerstate')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/enigma/media_player.py", line 187, in request_call
    async with self._opener.get(uri, auth=aiohttp.BasicAuth(self._username, self._password)) as resp:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 578, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1235, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1000, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.90.143:82 ssl:default [Connect call failed ('192.168.90.143', 82)]

```

thanks
Juergen

**Comment by cinzas** [comment]
@fft1010 , did you manage to get it working ?

**Comment by fft1010** [comment]
Hi @cinzas,
No I could not manage it, it seems to went away after another HA update or i de-installed the extension.

**Comment by cinzas** [comment]
Try and re-install :)

**Comment by fft1010** [comment]
I promise to do, but might take a while, as I now lived 7 month without it, ...
